export interface DemoCategory {
  id: string;
  name: string;
  slug: string;
  icon: string;
  _count: { listings: number };
}

export interface DemoUser {
  id: string;
  name: string;
  email: string;
  phone: string;
  avatarUrl: string;
  createdAt: string;
  reviewsWritten: any[];
  reviewsReceived: any[];
}

export interface DemoListing {
  id: string;
  title: string;
  description: string;
  spareDetails?: string | null;
  price: number;
  location: string;
  condition: string;
  imageUrl: string;
  status: string;
  views: number;
  boostTier?: string | null;
  boostExpiresAt?: string | null;
  createdAt: string;
  updatedAt: string;
  sellerId: string;
  categoryId: string;
  seller?: DemoUser;
  category?: DemoCategory;
}

export const DEMO_USERS: Record<string, DemoUser> = {
  ada: {
    id: "user-ada-101",
    name: "Ada Obi",
    email: "ada@sellquickest.ng",
    phone: "+234 803 123 4567",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    createdAt: "2024-01-15T10:00:00.000Z",
    reviewsWritten: [],
    reviewsReceived: [
      { id: "rev-1", rating: 5, comment: "Fast and reliable seller! Received the item exactly as described.", createdAt: "2024-02-10T12:00:00.000Z", reviewer: { name: "Emeka K." } },
      { id: "rev-2", rating: 5, comment: "Very polite, agreed to inspection before payment.", createdAt: "2024-03-01T14:30:00.000Z", reviewer: { name: "Fatima B." } }
    ],
  },
  chidi: {
    id: "user-chidi-102",
    name: "Chidi Eze",
    email: "chidi@sellquickest.ng",
    phone: "+234 802 987 6543",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    createdAt: "2024-01-20T11:00:00.000Z",
    reviewsWritten: [],
    reviewsReceived: [
      { id: "rev-3", rating: 5, comment: "Top-notch gadget! Fast delivery across Lagos.", createdAt: "2024-02-22T09:15:00.000Z", reviewer: { name: "Tunde O." } },
      { id: "rev-4", rating: 4, comment: "Good deal, phone battery was as stated.", createdAt: "2024-03-12T16:40:00.000Z", reviewer: { name: "Blessing A." } }
    ],
  },
};

export const DEMO_CATEGORIES: DemoCategory[] = [
  { id: "cat-vehicles", name: "Vehicles", slug: "vehicles", icon: "🚗", _count: { listings: 8 } },
  { id: "cat-property", name: "Property", slug: "property", icon: "🏠", _count: { listings: 6 } },
  { id: "cat-phones-tablets", name: "Phones & Tablets", slug: "phones-tablets", icon: "📱", _count: { listings: 12 } },
  { id: "cat-electronics", name: "Electronics", slug: "electronics", icon: "📺", _count: { listings: 7 } },
  { id: "cat-home", name: "Home, Furniture & Appliances", slug: "home", icon: "🛋️", _count: { listings: 5 } },
  { id: "cat-fashion", name: "Fashion", slug: "fashion", icon: "👗", _count: { listings: 9 } },
  { id: "cat-beauty", name: "Beauty & Personal Care", slug: "beauty", icon: "💄", _count: { listings: 4 } },
  { id: "cat-sports", name: "Sports, Arts & Outdoors", slug: "sports", icon: "⚽", _count: { listings: 3 } },
  { id: "cat-jobs", name: "Jobs", slug: "jobs", icon: "💼", _count: { listings: 4 } },
  { id: "cat-services", name: "Services", slug: "services", icon: "🔧", _count: { listings: 6 } },
  { id: "cat-pets", name: "Pets", slug: "pets", icon: "🐕", _count: { listings: 2 } },
  { id: "cat-agriculture", name: "Agriculture & Food", slug: "agriculture", icon: "🌾", _count: { listings: 5 } },
  { id: "cat-babies-kids", name: "Babies & Kids", slug: "babies-kids", icon: "🍼", _count: { listings: 3 } },
  { id: "cat-commercial-equipment", name: "Commercial Equipment & Tools", slug: "commercial-equipment", icon: "🏭", _count: { listings: 2 } },
  { id: "cat-repair-construction", name: "Repair & Construction", slug: "repair-construction", icon: "🏗️", _count: { listings: 2 } },
  { id: "cat-business-industry", name: "Business & Industry", slug: "business-industry", icon: "🏢", _count: { listings: 2 } },
];

export const DEMO_LISTINGS: DemoListing[] = [
  {
    id: "demo-listing-1",
    title: "Toyota Camry 2018 — tokunbo, low mileage",
    description: "Clean tokunbo Camry. AC ice cold, engine and gearbox sound. First owner in Nigeria. Inspection welcome in Ikeja.",
    price: 14500000,
    location: "Lagos, Ikeja",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 184,
    boostTier: "GOLD",
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-vehicles",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "demo-listing-2",
    title: "Honda Accord 2015 EX-L",
    description: "Well maintained Accord with leather seats and reverse camera. Duty complete. Serious buyers only.",
    price: 9800000,
    location: "Abuja, Wuse 2",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 92,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    sellerId: DEMO_USERS.ada.id,
    categoryId: "cat-vehicles",
    seller: DEMO_USERS.ada,
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "demo-listing-3",
    title: "iPhone 14 Pro Max 256GB — UK used",
    description: "Face ID working, battery 89%. Comes with box and charging cable. No FaceTime issues. Clean factory unlocked device.",
    price: 720000,
    location: "Lagos, Computer Village",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 310,
    boostTier: "FEATURED",
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    sellerId: DEMO_USERS.ada.id,
    categoryId: "cat-phones-tablets",
    seller: DEMO_USERS.ada,
    category: DEMO_CATEGORIES[2],
    spareDetails: JSON.stringify({
      brand: "Apple",
      model: "iPhone 14 Pro Max",
      storage: "256 GB",
      ram: "6 GB",
      operatingSystem: "iOS (Apple)",
      batteryHealth: "85% - 89%",
      simConfig: "Physical SIM + eSIM",
      network: "5G + 4G LTE Supported",
      lockStatus: "Factory Unlocked (Worldwide)",
      color: "Deep Purple",
      screenCondition: "Original Factory Screen (True Tone / 120Hz Working)",
      faceIdTouchId: "Face ID Working 100%",
    }),
  },
  {
    id: "demo-listing-4",
    title: "Samsung Galaxy S23 Ultra 512GB",
    description: "Brand new sealed. Dual SIM. 1 year warranty. Pickup at Computer Village or nationwide express delivery available.",
    price: 980000,
    location: "Lagos, Ikeja",
    condition: "New",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 220,
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-phones-tablets",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[2],
    spareDetails: JSON.stringify({
      brand: "Samsung",
      model: "Galaxy S23 Ultra",
      storage: "512 GB",
      ram: "12 GB",
      operatingSystem: "Android",
      batteryHealth: "5000 mAh+ (All-Day Battery)",
      simConfig: "Dual Physical SIM",
      network: "5G + 4G LTE Supported",
      color: "Phantom Black",
    }),
  },
  {
    id: "demo-listing-5",
    title: "MacBook Pro 14\" M2 — 16GB / 512GB",
    description: "Developer machine, battery cycle count under 80. Charger included. Keyboard English (US). Pristine condition.",
    price: 1850000,
    location: "Lagos, Victoria Island",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 145,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-electronics",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[3],
  },
  {
    id: "demo-listing-6",
    title: "Hisense 55\" 4K Smart TV",
    description: "Brand new, unopened carton. Netflix and YouTube apps pre-installed. Crystal clear HDR picture. Home delivery in Lagos.",
    price: 385000,
    location: "Lagos, Surulere",
    condition: "New",
    imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 78,
    createdAt: new Date(Date.now() - 15 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 3600000).toISOString(),
    sellerId: DEMO_USERS.ada.id,
    categoryId: "cat-electronics",
    seller: DEMO_USERS.ada,
    category: DEMO_CATEGORIES[3],
  },
  {
    id: "demo-listing-7",
    title: "PlayStation 5 Disc + 2 pads",
    description: "PS5 with FIFA 24 and God of War. Both DualSense pads working perfectly. Clean console with stand and power cable.",
    price: 620000,
    location: "Abuja, Gwarinpa",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 290,
    createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-electronics",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[3],
  },
  {
    id: "demo-listing-8",
    title: "3-bedroom flat for rent — Lekki Phase 1",
    description: "Spacious 3-bed with 24hr light, prepaid meter, and estate security. All rooms en-suite with balcony. Available immediately.",
    price: 4500000,
    location: "Lagos, Lekki",
    condition: "New",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 410,
    createdAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    sellerId: DEMO_USERS.ada.id,
    categoryId: "cat-property",
    seller: DEMO_USERS.ada,
    category: DEMO_CATEGORIES[1],
  },
  {
    id: "demo-listing-9",
    title: "Self-contain (studio) — Yaba",
    description: "Newly painted self-contain close to UNILAG. Constant running water and pre-paid meter. Suitable for students or young pros.",
    price: 650000,
    location: "Lagos, Yaba",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 195,
    createdAt: new Date(Date.now() - 22 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-property",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[1],
  },
  {
    id: "demo-listing-10",
    title: "6-seater L-shaped sofa (grey)",
    description: "Comfortable high-density fabric sofa, almost new. Moving out of state so selling fast. Pickup in Lekki.",
    price: 280000,
    location: "Lagos, Lekki",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 110,
    createdAt: new Date(Date.now() - 25 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 3600000).toISOString(),
    sellerId: DEMO_USERS.ada.id,
    categoryId: "cat-home",
    seller: DEMO_USERS.ada,
    category: DEMO_CATEGORIES[4],
  },
  {
    id: "demo-listing-11",
    title: "Thermocool double-door fridge 250L",
    description: "Working perfectly. Deep freezes quickly with low power consumption. Clean interior, no rust.",
    price: 195000,
    location: "Port Harcourt, GRA",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 64,
    createdAt: new Date(Date.now() - 28 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 28 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-home",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[4],
  },
  {
    id: "demo-listing-12",
    title: "Nike Dunk Low — size 43 (EU)",
    description: "Original Dunks, worn twice. Box and extra laces included. Authentic with verified receipt.",
    price: 85000,
    location: "Lagos, Lekki",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 130,
    createdAt: new Date(Date.now() - 30 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-fashion",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[5],
  },
  {
    id: "demo-listing-13",
    title: "Dyson Airwrap complete set (UK used)",
    description: "All attachments present and functioning. Smooth airflow, 220–240V direct plug. Transformer not needed.",
    price: 310000,
    location: "Lagos, Ikoyi",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1522338140262-f46f5913618a?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 88,
    createdAt: new Date(Date.now() - 35 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 3600000).toISOString(),
    sellerId: DEMO_USERS.ada.id,
    categoryId: "cat-beauty",
    seller: DEMO_USERS.ada,
    category: DEMO_CATEGORIES[6],
  },
  {
    id: "demo-listing-14",
    title: "Full gym dumbbell set 2–20kg with bench",
    description: "Hex rubberized dumbbells plus adjustable incline/decline bench. Perfect for a home gym. Heavy cast iron.",
    price: 175000,
    location: "Abuja, Maitama",
    condition: "Used",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 75,
    createdAt: new Date(Date.now() - 40 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-sports",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[7],
  },
  {
    id: "demo-listing-15",
    title: "Front-end Developer (Contract / Remote)",
    description: "Seeking a skilled React/Next.js developer for marketplace expansion. Competitive monthly pay with flexible hours.",
    price: 800000,
    location: "Lagos, Remote",
    condition: "New",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    status: "ACTIVE",
    views: 310,
    createdAt: new Date(Date.now() - 42 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 42 * 3600000).toISOString(),
    sellerId: DEMO_USERS.chidi.id,
    categoryId: "cat-jobs",
    seller: DEMO_USERS.chidi,
    category: DEMO_CATEGORIES[8],
  },
];
